// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pborm.proto

#ifndef PROTOBUF_pborm_2eproto__INCLUDED
#define PROTOBUF_pborm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pborm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pborm_2eproto();
void protobuf_AssignDesc_pborm_2eproto();
void protobuf_ShutdownFile_pborm_2eproto();

class OrmMsgReqSelect;
class OrmMsgRspSelect;
class OrmMsgReq;
class OrmMsgRsp;
class OrmMsgCB;
class OrmMsg;

enum OrmMsgOP {
  ORM_COMMAND = 0,
  ORM_INSERT = 1,
  ORM_DELETE = 2,
  ORM_SELECT = 3,
  ORM_UPDATE = 4,
  ORM_COUNT = 5
};
bool OrmMsgOP_IsValid(int value);
const OrmMsgOP OrmMsgOP_MIN = ORM_COMMAND;
const OrmMsgOP OrmMsgOP_MAX = ORM_COUNT;
const int OrmMsgOP_ARRAYSIZE = OrmMsgOP_MAX + 1;

const ::google::protobuf::EnumDescriptor* OrmMsgOP_descriptor();
inline const ::std::string& OrmMsgOP_Name(OrmMsgOP value) {
  return ::google::protobuf::internal::NameOfEnum(
    OrmMsgOP_descriptor(), value);
}
inline bool OrmMsgOP_Parse(
    const ::std::string& name, OrmMsgOP* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OrmMsgOP>(
    OrmMsgOP_descriptor(), name, value);
}
// ===================================================================

class OrmMsgReqSelect : public ::google::protobuf::Message {
 public:
  OrmMsgReqSelect();
  virtual ~OrmMsgReqSelect();

  OrmMsgReqSelect(const OrmMsgReqSelect& from);

  inline OrmMsgReqSelect& operator=(const OrmMsgReqSelect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrmMsgReqSelect& default_instance();

  void Swap(OrmMsgReqSelect* other);

  // implements Message ----------------------------------------------

  OrmMsgReqSelect* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrmMsgReqSelect& from);
  void MergeFrom(const OrmMsgReqSelect& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string where = 1;
  inline bool has_where() const;
  inline void clear_where();
  static const int kWhereFieldNumber = 1;
  inline const ::std::string& where() const;
  inline void set_where(const ::std::string& value);
  inline void set_where(const char* value);
  inline void set_where(const char* value, size_t size);
  inline ::std::string* mutable_where();
  inline ::std::string* release_where();
  inline void set_allocated_where(::std::string* where);

  // optional int32 offset = 2;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 2;
  inline ::google::protobuf::int32 offset() const;
  inline void set_offset(::google::protobuf::int32 value);

  // optional int32 limit = 3;
  inline bool has_limit() const;
  inline void clear_limit();
  static const int kLimitFieldNumber = 3;
  inline ::google::protobuf::int32 limit() const;
  inline void set_limit(::google::protobuf::int32 value);

  // optional string fields = 4;
  inline bool has_fields() const;
  inline void clear_fields();
  static const int kFieldsFieldNumber = 4;
  inline const ::std::string& fields() const;
  inline void set_fields(const ::std::string& value);
  inline void set_fields(const char* value);
  inline void set_fields(const char* value, size_t size);
  inline ::std::string* mutable_fields();
  inline ::std::string* release_fields();
  inline void set_allocated_fields(::std::string* fields);

  // optional int32 order = 5;
  inline bool has_order() const;
  inline void clear_order();
  static const int kOrderFieldNumber = 5;
  inline ::google::protobuf::int32 order() const;
  inline void set_order(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pborm.OrmMsgReqSelect)
 private:
  inline void set_has_where();
  inline void clear_has_where();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_limit();
  inline void clear_has_limit();
  inline void set_has_fields();
  inline void clear_has_fields();
  inline void set_has_order();
  inline void clear_has_order();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* where_;
  ::google::protobuf::int32 offset_;
  ::google::protobuf::int32 limit_;
  ::std::string* fields_;
  ::google::protobuf::int32 order_;
  friend void  protobuf_AddDesc_pborm_2eproto();
  friend void protobuf_AssignDesc_pborm_2eproto();
  friend void protobuf_ShutdownFile_pborm_2eproto();

  void InitAsDefaultInstance();
  static OrmMsgReqSelect* default_instance_;
};
// -------------------------------------------------------------------

class OrmMsgRspSelect : public ::google::protobuf::Message {
 public:
  OrmMsgRspSelect();
  virtual ~OrmMsgRspSelect();

  OrmMsgRspSelect(const OrmMsgRspSelect& from);

  inline OrmMsgRspSelect& operator=(const OrmMsgRspSelect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrmMsgRspSelect& default_instance();

  void Swap(OrmMsgRspSelect* other);

  // implements Message ----------------------------------------------

  OrmMsgRspSelect* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrmMsgRspSelect& from);
  void MergeFrom(const OrmMsgRspSelect& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .pborm.OrmMsgReqSelect req = 1;
  inline bool has_req() const;
  inline void clear_req();
  static const int kReqFieldNumber = 1;
  inline const ::pborm::OrmMsgReqSelect& req() const;
  inline ::pborm::OrmMsgReqSelect* mutable_req();
  inline ::pborm::OrmMsgReqSelect* release_req();
  inline void set_allocated_req(::pborm::OrmMsgReqSelect* req);

  // optional int32 total = 2;
  inline bool has_total() const;
  inline void clear_total();
  static const int kTotalFieldNumber = 2;
  inline ::google::protobuf::int32 total() const;
  inline void set_total(::google::protobuf::int32 value);

  // repeated bytes msgs = 3;
  inline int msgs_size() const;
  inline void clear_msgs();
  static const int kMsgsFieldNumber = 3;
  inline const ::std::string& msgs(int index) const;
  inline ::std::string* mutable_msgs(int index);
  inline void set_msgs(int index, const ::std::string& value);
  inline void set_msgs(int index, const char* value);
  inline void set_msgs(int index, const void* value, size_t size);
  inline ::std::string* add_msgs();
  inline void add_msgs(const ::std::string& value);
  inline void add_msgs(const char* value);
  inline void add_msgs(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& msgs() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_msgs();

  // @@protoc_insertion_point(class_scope:pborm.OrmMsgRspSelect)
 private:
  inline void set_has_req();
  inline void clear_has_req();
  inline void set_has_total();
  inline void clear_has_total();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::pborm::OrmMsgReqSelect* req_;
  ::google::protobuf::RepeatedPtrField< ::std::string> msgs_;
  ::google::protobuf::int32 total_;
  friend void  protobuf_AddDesc_pborm_2eproto();
  friend void protobuf_AssignDesc_pborm_2eproto();
  friend void protobuf_ShutdownFile_pborm_2eproto();

  void InitAsDefaultInstance();
  static OrmMsgRspSelect* default_instance_;
};
// -------------------------------------------------------------------

class OrmMsgReq : public ::google::protobuf::Message {
 public:
  OrmMsgReq();
  virtual ~OrmMsgReq();

  OrmMsgReq(const OrmMsgReq& from);

  inline OrmMsgReq& operator=(const OrmMsgReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrmMsgReq& default_instance();

  void Swap(OrmMsgReq* other);

  // implements Message ----------------------------------------------

  OrmMsgReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrmMsgReq& from);
  void MergeFrom(const OrmMsgReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes msg_data = 1;
  inline bool has_msg_data() const;
  inline void clear_msg_data();
  static const int kMsgDataFieldNumber = 1;
  inline const ::std::string& msg_data() const;
  inline void set_msg_data(const ::std::string& value);
  inline void set_msg_data(const char* value);
  inline void set_msg_data(const void* value, size_t size);
  inline ::std::string* mutable_msg_data();
  inline ::std::string* release_msg_data();
  inline void set_allocated_msg_data(::std::string* msg_data);

  // optional .pborm.OrmMsgReqSelect select = 2;
  inline bool has_select() const;
  inline void clear_select();
  static const int kSelectFieldNumber = 2;
  inline const ::pborm::OrmMsgReqSelect& select() const;
  inline ::pborm::OrmMsgReqSelect* mutable_select();
  inline ::pborm::OrmMsgReqSelect* release_select();
  inline void set_allocated_select(::pborm::OrmMsgReqSelect* select);

  // @@protoc_insertion_point(class_scope:pborm.OrmMsgReq)
 private:
  inline void set_has_msg_data();
  inline void clear_has_msg_data();
  inline void set_has_select();
  inline void clear_has_select();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* msg_data_;
  ::pborm::OrmMsgReqSelect* select_;
  friend void  protobuf_AddDesc_pborm_2eproto();
  friend void protobuf_AssignDesc_pborm_2eproto();
  friend void protobuf_ShutdownFile_pborm_2eproto();

  void InitAsDefaultInstance();
  static OrmMsgReq* default_instance_;
};
// -------------------------------------------------------------------

class OrmMsgRsp : public ::google::protobuf::Message {
 public:
  OrmMsgRsp();
  virtual ~OrmMsgRsp();

  OrmMsgRsp(const OrmMsgRsp& from);

  inline OrmMsgRsp& operator=(const OrmMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrmMsgRsp& default_instance();

  void Swap(OrmMsgRsp* other);

  // implements Message ----------------------------------------------

  OrmMsgRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrmMsgRsp& from);
  void MergeFrom(const OrmMsgRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 count = 1;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 1;
  inline ::google::protobuf::int32 count() const;
  inline void set_count(::google::protobuf::int32 value);

  // optional int32 err_no = 2;
  inline bool has_err_no() const;
  inline void clear_err_no();
  static const int kErrNoFieldNumber = 2;
  inline ::google::protobuf::int32 err_no() const;
  inline void set_err_no(::google::protobuf::int32 value);

  // optional string err_msg = 3;
  inline bool has_err_msg() const;
  inline void clear_err_msg();
  static const int kErrMsgFieldNumber = 3;
  inline const ::std::string& err_msg() const;
  inline void set_err_msg(const ::std::string& value);
  inline void set_err_msg(const char* value);
  inline void set_err_msg(const char* value, size_t size);
  inline ::std::string* mutable_err_msg();
  inline ::std::string* release_err_msg();
  inline void set_allocated_err_msg(::std::string* err_msg);

  // optional .pborm.OrmMsgRspSelect select = 4;
  inline bool has_select() const;
  inline void clear_select();
  static const int kSelectFieldNumber = 4;
  inline const ::pborm::OrmMsgRspSelect& select() const;
  inline ::pborm::OrmMsgRspSelect* mutable_select();
  inline ::pborm::OrmMsgRspSelect* release_select();
  inline void set_allocated_select(::pborm::OrmMsgRspSelect* select);

  // @@protoc_insertion_point(class_scope:pborm.OrmMsgRsp)
 private:
  inline void set_has_count();
  inline void clear_has_count();
  inline void set_has_err_no();
  inline void clear_has_err_no();
  inline void set_has_err_msg();
  inline void clear_has_err_msg();
  inline void set_has_select();
  inline void clear_has_select();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 count_;
  ::google::protobuf::int32 err_no_;
  ::std::string* err_msg_;
  ::pborm::OrmMsgRspSelect* select_;
  friend void  protobuf_AddDesc_pborm_2eproto();
  friend void protobuf_AssignDesc_pborm_2eproto();
  friend void protobuf_ShutdownFile_pborm_2eproto();

  void InitAsDefaultInstance();
  static OrmMsgRsp* default_instance_;
};
// -------------------------------------------------------------------

class OrmMsgCB : public ::google::protobuf::Message {
 public:
  OrmMsgCB();
  virtual ~OrmMsgCB();

  OrmMsgCB(const OrmMsgCB& from);

  inline OrmMsgCB& operator=(const OrmMsgCB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrmMsgCB& default_instance();

  void Swap(OrmMsgCB* other);

  // implements Message ----------------------------------------------

  OrmMsgCB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrmMsgCB& from);
  void MergeFrom(const OrmMsgCB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // optional int64 cookie = 2;
  inline bool has_cookie() const;
  inline void clear_cookie();
  static const int kCookieFieldNumber = 2;
  inline ::google::protobuf::int64 cookie() const;
  inline void set_cookie(::google::protobuf::int64 value);

  // optional uint32 seq = 3;
  inline bool has_seq() const;
  inline void clear_seq();
  static const int kSeqFieldNumber = 3;
  inline ::google::protobuf::uint32 seq() const;
  inline void set_seq(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pborm.OrmMsgCB)
 private:
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_cookie();
  inline void clear_has_cookie();
  inline void set_has_seq();
  inline void clear_has_seq();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* data_;
  ::google::protobuf::int64 cookie_;
  ::google::protobuf::uint32 seq_;
  friend void  protobuf_AddDesc_pborm_2eproto();
  friend void protobuf_AssignDesc_pborm_2eproto();
  friend void protobuf_ShutdownFile_pborm_2eproto();

  void InitAsDefaultInstance();
  static OrmMsgCB* default_instance_;
};
// -------------------------------------------------------------------

class OrmMsg : public ::google::protobuf::Message {
 public:
  OrmMsg();
  virtual ~OrmMsg();

  OrmMsg(const OrmMsg& from);

  inline OrmMsg& operator=(const OrmMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrmMsg& default_instance();

  void Swap(OrmMsg* other);

  // implements Message ----------------------------------------------

  OrmMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrmMsg& from);
  void MergeFrom(const OrmMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string msg_full_type_name = 1;
  inline bool has_msg_full_type_name() const;
  inline void clear_msg_full_type_name();
  static const int kMsgFullTypeNameFieldNumber = 1;
  inline const ::std::string& msg_full_type_name() const;
  inline void set_msg_full_type_name(const ::std::string& value);
  inline void set_msg_full_type_name(const char* value);
  inline void set_msg_full_type_name(const char* value, size_t size);
  inline ::std::string* mutable_msg_full_type_name();
  inline ::std::string* release_msg_full_type_name();
  inline void set_allocated_msg_full_type_name(::std::string* msg_full_type_name);

  // required .pborm.OrmMsgOP op = 2;
  inline bool has_op() const;
  inline void clear_op();
  static const int kOpFieldNumber = 2;
  inline ::pborm::OrmMsgOP op() const;
  inline void set_op(::pborm::OrmMsgOP value);

  // optional .pborm.OrmMsgReq req = 3;
  inline bool has_req() const;
  inline void clear_req();
  static const int kReqFieldNumber = 3;
  inline const ::pborm::OrmMsgReq& req() const;
  inline ::pborm::OrmMsgReq* mutable_req();
  inline ::pborm::OrmMsgReq* release_req();
  inline void set_allocated_req(::pborm::OrmMsgReq* req);

  // optional .pborm.OrmMsgRsp rsp = 4;
  inline bool has_rsp() const;
  inline void clear_rsp();
  static const int kRspFieldNumber = 4;
  inline const ::pborm::OrmMsgRsp& rsp() const;
  inline ::pborm::OrmMsgRsp* mutable_rsp();
  inline ::pborm::OrmMsgRsp* release_rsp();
  inline void set_allocated_rsp(::pborm::OrmMsgRsp* rsp);

  // optional .pborm.OrmMsgCB cb = 5;
  inline bool has_cb() const;
  inline void clear_cb();
  static const int kCbFieldNumber = 5;
  inline const ::pborm::OrmMsgCB& cb() const;
  inline ::pborm::OrmMsgCB* mutable_cb();
  inline ::pborm::OrmMsgCB* release_cb();
  inline void set_allocated_cb(::pborm::OrmMsgCB* cb);

  // @@protoc_insertion_point(class_scope:pborm.OrmMsg)
 private:
  inline void set_has_msg_full_type_name();
  inline void clear_has_msg_full_type_name();
  inline void set_has_op();
  inline void clear_has_op();
  inline void set_has_req();
  inline void clear_has_req();
  inline void set_has_rsp();
  inline void clear_has_rsp();
  inline void set_has_cb();
  inline void clear_has_cb();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* msg_full_type_name_;
  ::pborm::OrmMsgReq* req_;
  ::pborm::OrmMsgRsp* rsp_;
  ::pborm::OrmMsgCB* cb_;
  int op_;
  friend void  protobuf_AddDesc_pborm_2eproto();
  friend void protobuf_AssignDesc_pborm_2eproto();
  friend void protobuf_ShutdownFile_pborm_2eproto();

  void InitAsDefaultInstance();
  static OrmMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// OrmMsgReqSelect

// optional string where = 1;
inline bool OrmMsgReqSelect::has_where() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrmMsgReqSelect::set_has_where() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrmMsgReqSelect::clear_has_where() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrmMsgReqSelect::clear_where() {
  if (where_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    where_->clear();
  }
  clear_has_where();
}
inline const ::std::string& OrmMsgReqSelect::where() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgReqSelect.where)
  return *where_;
}
inline void OrmMsgReqSelect::set_where(const ::std::string& value) {
  set_has_where();
  if (where_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    where_ = new ::std::string;
  }
  where_->assign(value);
  // @@protoc_insertion_point(field_set:pborm.OrmMsgReqSelect.where)
}
inline void OrmMsgReqSelect::set_where(const char* value) {
  set_has_where();
  if (where_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    where_ = new ::std::string;
  }
  where_->assign(value);
  // @@protoc_insertion_point(field_set_char:pborm.OrmMsgReqSelect.where)
}
inline void OrmMsgReqSelect::set_where(const char* value, size_t size) {
  set_has_where();
  if (where_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    where_ = new ::std::string;
  }
  where_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pborm.OrmMsgReqSelect.where)
}
inline ::std::string* OrmMsgReqSelect::mutable_where() {
  set_has_where();
  if (where_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    where_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgReqSelect.where)
  return where_;
}
inline ::std::string* OrmMsgReqSelect::release_where() {
  clear_has_where();
  if (where_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = where_;
    where_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrmMsgReqSelect::set_allocated_where(::std::string* where) {
  if (where_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete where_;
  }
  if (where) {
    set_has_where();
    where_ = where;
  } else {
    clear_has_where();
    where_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsgReqSelect.where)
}

// optional int32 offset = 2;
inline bool OrmMsgReqSelect::has_offset() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrmMsgReqSelect::set_has_offset() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrmMsgReqSelect::clear_has_offset() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrmMsgReqSelect::clear_offset() {
  offset_ = 0;
  clear_has_offset();
}
inline ::google::protobuf::int32 OrmMsgReqSelect::offset() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgReqSelect.offset)
  return offset_;
}
inline void OrmMsgReqSelect::set_offset(::google::protobuf::int32 value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsgReqSelect.offset)
}

// optional int32 limit = 3;
inline bool OrmMsgReqSelect::has_limit() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OrmMsgReqSelect::set_has_limit() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OrmMsgReqSelect::clear_has_limit() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OrmMsgReqSelect::clear_limit() {
  limit_ = 0;
  clear_has_limit();
}
inline ::google::protobuf::int32 OrmMsgReqSelect::limit() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgReqSelect.limit)
  return limit_;
}
inline void OrmMsgReqSelect::set_limit(::google::protobuf::int32 value) {
  set_has_limit();
  limit_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsgReqSelect.limit)
}

// optional string fields = 4;
inline bool OrmMsgReqSelect::has_fields() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OrmMsgReqSelect::set_has_fields() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OrmMsgReqSelect::clear_has_fields() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OrmMsgReqSelect::clear_fields() {
  if (fields_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fields_->clear();
  }
  clear_has_fields();
}
inline const ::std::string& OrmMsgReqSelect::fields() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgReqSelect.fields)
  return *fields_;
}
inline void OrmMsgReqSelect::set_fields(const ::std::string& value) {
  set_has_fields();
  if (fields_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fields_ = new ::std::string;
  }
  fields_->assign(value);
  // @@protoc_insertion_point(field_set:pborm.OrmMsgReqSelect.fields)
}
inline void OrmMsgReqSelect::set_fields(const char* value) {
  set_has_fields();
  if (fields_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fields_ = new ::std::string;
  }
  fields_->assign(value);
  // @@protoc_insertion_point(field_set_char:pborm.OrmMsgReqSelect.fields)
}
inline void OrmMsgReqSelect::set_fields(const char* value, size_t size) {
  set_has_fields();
  if (fields_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fields_ = new ::std::string;
  }
  fields_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pborm.OrmMsgReqSelect.fields)
}
inline ::std::string* OrmMsgReqSelect::mutable_fields() {
  set_has_fields();
  if (fields_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fields_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgReqSelect.fields)
  return fields_;
}
inline ::std::string* OrmMsgReqSelect::release_fields() {
  clear_has_fields();
  if (fields_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = fields_;
    fields_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrmMsgReqSelect::set_allocated_fields(::std::string* fields) {
  if (fields_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete fields_;
  }
  if (fields) {
    set_has_fields();
    fields_ = fields;
  } else {
    clear_has_fields();
    fields_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsgReqSelect.fields)
}

// optional int32 order = 5;
inline bool OrmMsgReqSelect::has_order() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OrmMsgReqSelect::set_has_order() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OrmMsgReqSelect::clear_has_order() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OrmMsgReqSelect::clear_order() {
  order_ = 0;
  clear_has_order();
}
inline ::google::protobuf::int32 OrmMsgReqSelect::order() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgReqSelect.order)
  return order_;
}
inline void OrmMsgReqSelect::set_order(::google::protobuf::int32 value) {
  set_has_order();
  order_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsgReqSelect.order)
}

// -------------------------------------------------------------------

// OrmMsgRspSelect

// required .pborm.OrmMsgReqSelect req = 1;
inline bool OrmMsgRspSelect::has_req() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrmMsgRspSelect::set_has_req() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrmMsgRspSelect::clear_has_req() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrmMsgRspSelect::clear_req() {
  if (req_ != NULL) req_->::pborm::OrmMsgReqSelect::Clear();
  clear_has_req();
}
inline const ::pborm::OrmMsgReqSelect& OrmMsgRspSelect::req() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgRspSelect.req)
  return req_ != NULL ? *req_ : *default_instance_->req_;
}
inline ::pborm::OrmMsgReqSelect* OrmMsgRspSelect::mutable_req() {
  set_has_req();
  if (req_ == NULL) req_ = new ::pborm::OrmMsgReqSelect;
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgRspSelect.req)
  return req_;
}
inline ::pborm::OrmMsgReqSelect* OrmMsgRspSelect::release_req() {
  clear_has_req();
  ::pborm::OrmMsgReqSelect* temp = req_;
  req_ = NULL;
  return temp;
}
inline void OrmMsgRspSelect::set_allocated_req(::pborm::OrmMsgReqSelect* req) {
  delete req_;
  req_ = req;
  if (req) {
    set_has_req();
  } else {
    clear_has_req();
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsgRspSelect.req)
}

// optional int32 total = 2;
inline bool OrmMsgRspSelect::has_total() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrmMsgRspSelect::set_has_total() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrmMsgRspSelect::clear_has_total() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrmMsgRspSelect::clear_total() {
  total_ = 0;
  clear_has_total();
}
inline ::google::protobuf::int32 OrmMsgRspSelect::total() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgRspSelect.total)
  return total_;
}
inline void OrmMsgRspSelect::set_total(::google::protobuf::int32 value) {
  set_has_total();
  total_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsgRspSelect.total)
}

// repeated bytes msgs = 3;
inline int OrmMsgRspSelect::msgs_size() const {
  return msgs_.size();
}
inline void OrmMsgRspSelect::clear_msgs() {
  msgs_.Clear();
}
inline const ::std::string& OrmMsgRspSelect::msgs(int index) const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgRspSelect.msgs)
  return msgs_.Get(index);
}
inline ::std::string* OrmMsgRspSelect::mutable_msgs(int index) {
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgRspSelect.msgs)
  return msgs_.Mutable(index);
}
inline void OrmMsgRspSelect::set_msgs(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:pborm.OrmMsgRspSelect.msgs)
  msgs_.Mutable(index)->assign(value);
}
inline void OrmMsgRspSelect::set_msgs(int index, const char* value) {
  msgs_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:pborm.OrmMsgRspSelect.msgs)
}
inline void OrmMsgRspSelect::set_msgs(int index, const void* value, size_t size) {
  msgs_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pborm.OrmMsgRspSelect.msgs)
}
inline ::std::string* OrmMsgRspSelect::add_msgs() {
  return msgs_.Add();
}
inline void OrmMsgRspSelect::add_msgs(const ::std::string& value) {
  msgs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:pborm.OrmMsgRspSelect.msgs)
}
inline void OrmMsgRspSelect::add_msgs(const char* value) {
  msgs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:pborm.OrmMsgRspSelect.msgs)
}
inline void OrmMsgRspSelect::add_msgs(const void* value, size_t size) {
  msgs_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:pborm.OrmMsgRspSelect.msgs)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
OrmMsgRspSelect::msgs() const {
  // @@protoc_insertion_point(field_list:pborm.OrmMsgRspSelect.msgs)
  return msgs_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
OrmMsgRspSelect::mutable_msgs() {
  // @@protoc_insertion_point(field_mutable_list:pborm.OrmMsgRspSelect.msgs)
  return &msgs_;
}

// -------------------------------------------------------------------

// OrmMsgReq

// optional bytes msg_data = 1;
inline bool OrmMsgReq::has_msg_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrmMsgReq::set_has_msg_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrmMsgReq::clear_has_msg_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrmMsgReq::clear_msg_data() {
  if (msg_data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_->clear();
  }
  clear_has_msg_data();
}
inline const ::std::string& OrmMsgReq::msg_data() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgReq.msg_data)
  return *msg_data_;
}
inline void OrmMsgReq::set_msg_data(const ::std::string& value) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(value);
  // @@protoc_insertion_point(field_set:pborm.OrmMsgReq.msg_data)
}
inline void OrmMsgReq::set_msg_data(const char* value) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(value);
  // @@protoc_insertion_point(field_set_char:pborm.OrmMsgReq.msg_data)
}
inline void OrmMsgReq::set_msg_data(const void* value, size_t size) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pborm.OrmMsgReq.msg_data)
}
inline ::std::string* OrmMsgReq::mutable_msg_data() {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgReq.msg_data)
  return msg_data_;
}
inline ::std::string* OrmMsgReq::release_msg_data() {
  clear_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = msg_data_;
    msg_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrmMsgReq::set_allocated_msg_data(::std::string* msg_data) {
  if (msg_data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_data_;
  }
  if (msg_data) {
    set_has_msg_data();
    msg_data_ = msg_data;
  } else {
    clear_has_msg_data();
    msg_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsgReq.msg_data)
}

// optional .pborm.OrmMsgReqSelect select = 2;
inline bool OrmMsgReq::has_select() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrmMsgReq::set_has_select() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrmMsgReq::clear_has_select() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrmMsgReq::clear_select() {
  if (select_ != NULL) select_->::pborm::OrmMsgReqSelect::Clear();
  clear_has_select();
}
inline const ::pborm::OrmMsgReqSelect& OrmMsgReq::select() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgReq.select)
  return select_ != NULL ? *select_ : *default_instance_->select_;
}
inline ::pborm::OrmMsgReqSelect* OrmMsgReq::mutable_select() {
  set_has_select();
  if (select_ == NULL) select_ = new ::pborm::OrmMsgReqSelect;
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgReq.select)
  return select_;
}
inline ::pborm::OrmMsgReqSelect* OrmMsgReq::release_select() {
  clear_has_select();
  ::pborm::OrmMsgReqSelect* temp = select_;
  select_ = NULL;
  return temp;
}
inline void OrmMsgReq::set_allocated_select(::pborm::OrmMsgReqSelect* select) {
  delete select_;
  select_ = select;
  if (select) {
    set_has_select();
  } else {
    clear_has_select();
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsgReq.select)
}

// -------------------------------------------------------------------

// OrmMsgRsp

// optional int32 count = 1;
inline bool OrmMsgRsp::has_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrmMsgRsp::set_has_count() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrmMsgRsp::clear_has_count() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrmMsgRsp::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::google::protobuf::int32 OrmMsgRsp::count() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgRsp.count)
  return count_;
}
inline void OrmMsgRsp::set_count(::google::protobuf::int32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsgRsp.count)
}

// optional int32 err_no = 2;
inline bool OrmMsgRsp::has_err_no() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrmMsgRsp::set_has_err_no() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrmMsgRsp::clear_has_err_no() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrmMsgRsp::clear_err_no() {
  err_no_ = 0;
  clear_has_err_no();
}
inline ::google::protobuf::int32 OrmMsgRsp::err_no() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgRsp.err_no)
  return err_no_;
}
inline void OrmMsgRsp::set_err_no(::google::protobuf::int32 value) {
  set_has_err_no();
  err_no_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsgRsp.err_no)
}

// optional string err_msg = 3;
inline bool OrmMsgRsp::has_err_msg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OrmMsgRsp::set_has_err_msg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OrmMsgRsp::clear_has_err_msg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OrmMsgRsp::clear_err_msg() {
  if (err_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    err_msg_->clear();
  }
  clear_has_err_msg();
}
inline const ::std::string& OrmMsgRsp::err_msg() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgRsp.err_msg)
  return *err_msg_;
}
inline void OrmMsgRsp::set_err_msg(const ::std::string& value) {
  set_has_err_msg();
  if (err_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    err_msg_ = new ::std::string;
  }
  err_msg_->assign(value);
  // @@protoc_insertion_point(field_set:pborm.OrmMsgRsp.err_msg)
}
inline void OrmMsgRsp::set_err_msg(const char* value) {
  set_has_err_msg();
  if (err_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    err_msg_ = new ::std::string;
  }
  err_msg_->assign(value);
  // @@protoc_insertion_point(field_set_char:pborm.OrmMsgRsp.err_msg)
}
inline void OrmMsgRsp::set_err_msg(const char* value, size_t size) {
  set_has_err_msg();
  if (err_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    err_msg_ = new ::std::string;
  }
  err_msg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pborm.OrmMsgRsp.err_msg)
}
inline ::std::string* OrmMsgRsp::mutable_err_msg() {
  set_has_err_msg();
  if (err_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    err_msg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgRsp.err_msg)
  return err_msg_;
}
inline ::std::string* OrmMsgRsp::release_err_msg() {
  clear_has_err_msg();
  if (err_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = err_msg_;
    err_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrmMsgRsp::set_allocated_err_msg(::std::string* err_msg) {
  if (err_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete err_msg_;
  }
  if (err_msg) {
    set_has_err_msg();
    err_msg_ = err_msg;
  } else {
    clear_has_err_msg();
    err_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsgRsp.err_msg)
}

// optional .pborm.OrmMsgRspSelect select = 4;
inline bool OrmMsgRsp::has_select() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OrmMsgRsp::set_has_select() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OrmMsgRsp::clear_has_select() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OrmMsgRsp::clear_select() {
  if (select_ != NULL) select_->::pborm::OrmMsgRspSelect::Clear();
  clear_has_select();
}
inline const ::pborm::OrmMsgRspSelect& OrmMsgRsp::select() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgRsp.select)
  return select_ != NULL ? *select_ : *default_instance_->select_;
}
inline ::pborm::OrmMsgRspSelect* OrmMsgRsp::mutable_select() {
  set_has_select();
  if (select_ == NULL) select_ = new ::pborm::OrmMsgRspSelect;
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgRsp.select)
  return select_;
}
inline ::pborm::OrmMsgRspSelect* OrmMsgRsp::release_select() {
  clear_has_select();
  ::pborm::OrmMsgRspSelect* temp = select_;
  select_ = NULL;
  return temp;
}
inline void OrmMsgRsp::set_allocated_select(::pborm::OrmMsgRspSelect* select) {
  delete select_;
  select_ = select;
  if (select) {
    set_has_select();
  } else {
    clear_has_select();
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsgRsp.select)
}

// -------------------------------------------------------------------

// OrmMsgCB

// optional bytes data = 1;
inline bool OrmMsgCB::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrmMsgCB::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrmMsgCB::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrmMsgCB::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& OrmMsgCB::data() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgCB.data)
  return *data_;
}
inline void OrmMsgCB::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:pborm.OrmMsgCB.data)
}
inline void OrmMsgCB::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:pborm.OrmMsgCB.data)
}
inline void OrmMsgCB::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pborm.OrmMsgCB.data)
}
inline ::std::string* OrmMsgCB::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsgCB.data)
  return data_;
}
inline ::std::string* OrmMsgCB::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrmMsgCB::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsgCB.data)
}

// optional int64 cookie = 2;
inline bool OrmMsgCB::has_cookie() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrmMsgCB::set_has_cookie() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrmMsgCB::clear_has_cookie() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrmMsgCB::clear_cookie() {
  cookie_ = GOOGLE_LONGLONG(0);
  clear_has_cookie();
}
inline ::google::protobuf::int64 OrmMsgCB::cookie() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgCB.cookie)
  return cookie_;
}
inline void OrmMsgCB::set_cookie(::google::protobuf::int64 value) {
  set_has_cookie();
  cookie_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsgCB.cookie)
}

// optional uint32 seq = 3;
inline bool OrmMsgCB::has_seq() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OrmMsgCB::set_has_seq() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OrmMsgCB::clear_has_seq() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OrmMsgCB::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
inline ::google::protobuf::uint32 OrmMsgCB::seq() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsgCB.seq)
  return seq_;
}
inline void OrmMsgCB::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsgCB.seq)
}

// -------------------------------------------------------------------

// OrmMsg

// required string msg_full_type_name = 1;
inline bool OrmMsg::has_msg_full_type_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrmMsg::set_has_msg_full_type_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrmMsg::clear_has_msg_full_type_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrmMsg::clear_msg_full_type_name() {
  if (msg_full_type_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_full_type_name_->clear();
  }
  clear_has_msg_full_type_name();
}
inline const ::std::string& OrmMsg::msg_full_type_name() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsg.msg_full_type_name)
  return *msg_full_type_name_;
}
inline void OrmMsg::set_msg_full_type_name(const ::std::string& value) {
  set_has_msg_full_type_name();
  if (msg_full_type_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_full_type_name_ = new ::std::string;
  }
  msg_full_type_name_->assign(value);
  // @@protoc_insertion_point(field_set:pborm.OrmMsg.msg_full_type_name)
}
inline void OrmMsg::set_msg_full_type_name(const char* value) {
  set_has_msg_full_type_name();
  if (msg_full_type_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_full_type_name_ = new ::std::string;
  }
  msg_full_type_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:pborm.OrmMsg.msg_full_type_name)
}
inline void OrmMsg::set_msg_full_type_name(const char* value, size_t size) {
  set_has_msg_full_type_name();
  if (msg_full_type_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_full_type_name_ = new ::std::string;
  }
  msg_full_type_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pborm.OrmMsg.msg_full_type_name)
}
inline ::std::string* OrmMsg::mutable_msg_full_type_name() {
  set_has_msg_full_type_name();
  if (msg_full_type_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_full_type_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsg.msg_full_type_name)
  return msg_full_type_name_;
}
inline ::std::string* OrmMsg::release_msg_full_type_name() {
  clear_has_msg_full_type_name();
  if (msg_full_type_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = msg_full_type_name_;
    msg_full_type_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrmMsg::set_allocated_msg_full_type_name(::std::string* msg_full_type_name) {
  if (msg_full_type_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_full_type_name_;
  }
  if (msg_full_type_name) {
    set_has_msg_full_type_name();
    msg_full_type_name_ = msg_full_type_name;
  } else {
    clear_has_msg_full_type_name();
    msg_full_type_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsg.msg_full_type_name)
}

// required .pborm.OrmMsgOP op = 2;
inline bool OrmMsg::has_op() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrmMsg::set_has_op() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrmMsg::clear_has_op() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrmMsg::clear_op() {
  op_ = 0;
  clear_has_op();
}
inline ::pborm::OrmMsgOP OrmMsg::op() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsg.op)
  return static_cast< ::pborm::OrmMsgOP >(op_);
}
inline void OrmMsg::set_op(::pborm::OrmMsgOP value) {
  assert(::pborm::OrmMsgOP_IsValid(value));
  set_has_op();
  op_ = value;
  // @@protoc_insertion_point(field_set:pborm.OrmMsg.op)
}

// optional .pborm.OrmMsgReq req = 3;
inline bool OrmMsg::has_req() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OrmMsg::set_has_req() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OrmMsg::clear_has_req() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OrmMsg::clear_req() {
  if (req_ != NULL) req_->::pborm::OrmMsgReq::Clear();
  clear_has_req();
}
inline const ::pborm::OrmMsgReq& OrmMsg::req() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsg.req)
  return req_ != NULL ? *req_ : *default_instance_->req_;
}
inline ::pborm::OrmMsgReq* OrmMsg::mutable_req() {
  set_has_req();
  if (req_ == NULL) req_ = new ::pborm::OrmMsgReq;
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsg.req)
  return req_;
}
inline ::pborm::OrmMsgReq* OrmMsg::release_req() {
  clear_has_req();
  ::pborm::OrmMsgReq* temp = req_;
  req_ = NULL;
  return temp;
}
inline void OrmMsg::set_allocated_req(::pborm::OrmMsgReq* req) {
  delete req_;
  req_ = req;
  if (req) {
    set_has_req();
  } else {
    clear_has_req();
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsg.req)
}

// optional .pborm.OrmMsgRsp rsp = 4;
inline bool OrmMsg::has_rsp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OrmMsg::set_has_rsp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OrmMsg::clear_has_rsp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OrmMsg::clear_rsp() {
  if (rsp_ != NULL) rsp_->::pborm::OrmMsgRsp::Clear();
  clear_has_rsp();
}
inline const ::pborm::OrmMsgRsp& OrmMsg::rsp() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsg.rsp)
  return rsp_ != NULL ? *rsp_ : *default_instance_->rsp_;
}
inline ::pborm::OrmMsgRsp* OrmMsg::mutable_rsp() {
  set_has_rsp();
  if (rsp_ == NULL) rsp_ = new ::pborm::OrmMsgRsp;
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsg.rsp)
  return rsp_;
}
inline ::pborm::OrmMsgRsp* OrmMsg::release_rsp() {
  clear_has_rsp();
  ::pborm::OrmMsgRsp* temp = rsp_;
  rsp_ = NULL;
  return temp;
}
inline void OrmMsg::set_allocated_rsp(::pborm::OrmMsgRsp* rsp) {
  delete rsp_;
  rsp_ = rsp;
  if (rsp) {
    set_has_rsp();
  } else {
    clear_has_rsp();
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsg.rsp)
}

// optional .pborm.OrmMsgCB cb = 5;
inline bool OrmMsg::has_cb() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OrmMsg::set_has_cb() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OrmMsg::clear_has_cb() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OrmMsg::clear_cb() {
  if (cb_ != NULL) cb_->::pborm::OrmMsgCB::Clear();
  clear_has_cb();
}
inline const ::pborm::OrmMsgCB& OrmMsg::cb() const {
  // @@protoc_insertion_point(field_get:pborm.OrmMsg.cb)
  return cb_ != NULL ? *cb_ : *default_instance_->cb_;
}
inline ::pborm::OrmMsgCB* OrmMsg::mutable_cb() {
  set_has_cb();
  if (cb_ == NULL) cb_ = new ::pborm::OrmMsgCB;
  // @@protoc_insertion_point(field_mutable:pborm.OrmMsg.cb)
  return cb_;
}
inline ::pborm::OrmMsgCB* OrmMsg::release_cb() {
  clear_has_cb();
  ::pborm::OrmMsgCB* temp = cb_;
  cb_ = NULL;
  return temp;
}
inline void OrmMsg::set_allocated_cb(::pborm::OrmMsgCB* cb) {
  delete cb_;
  cb_ = cb;
  if (cb) {
    set_has_cb();
  } else {
    clear_has_cb();
  }
  // @@protoc_insertion_point(field_set_allocated:pborm.OrmMsg.cb)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pborm

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pborm::OrmMsgOP> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pborm::OrmMsgOP>() {
  return ::pborm::OrmMsgOP_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pborm_2eproto__INCLUDED
